package com.gromero.portal.visor.constantes;

public class ConstantesBD {

	public static final String COTIZACION1 = new StringBuilder("SELECT  A.NUMOPE,B.NROOI, B.SIGLA || B.SERIE AS CONTENEDOR,J.CODSRVCO,I.NRODOCID,A.FECOPE,K.CODMON, " )
    .append("F.IMPSCPR AS IMP_SILE,J.CDRFCODMAT,J.NCCSAP,A.FECOPE,C.NROPEDI,C.FLGPEDI,C.IMPPEDI AS IMP_PEDIDO," )
    .append("CASE WHEN D.IDCSTCNTCL IS NOT NULL THEN 'COTIZADO' END AS TIPO, J.DESSRVCO, I.RZINLO,C.IDOPEPED " )
    .append("FROM SICEX.TBN011 A " )
    .append("INNER JOIN SICEX.TBN014 B ON A.IDOPE=B.IDOPE AND B.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN016 C ON C.IDOPETCOI=B.IDOPETCOI  AND C.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN013 D ON D.IDOPECST=C.IDOPECST AND D.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN006 E ON E.IDCSTCNTCL=D.IDCSTCNTCL AND E.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN002 F ON F.IDCONDET=E.IDCONDET AND F.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN001 G ON G.IDCONPRV=F.IDCONPRV AND G.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM031 H ON H.IDINLOUNRL=G.IDINLOUNRL AND H.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM018 I ON I.IDINLOCTR=H.IDINLOCTR AND I.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM020 J ON J.IDSRVCO=F.IDSRVCO AND J.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM013 K ON K.IDMON=F.IDMON AND K.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN004 M ON M.IDCNTCLCAB=A.IDCNTCLCAB AND M.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN005 N ON N.IDCNTCLCAB=M.IDCNTCLCAB AND N.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN012 O ON O.IDOPEVTA=D.IDOPEVTA  AND O.IDOPE=A.IDOPE AND O.IDCNTCLDET=N.IDCNTCLDET AND O.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN015 P ON P.IDOPETCOI=B.IDOPETCOI AND P.IDOPEVTA=O.IDOPEVTA AND P.SACRG=1 " )
    .append("WHERE A.SACRG=1 AND D.ESTOPECST='A' AND C.NROPEDI=0 AND " )
    .append("I.NRODOCID NOT IN (SELECT RUCPRO FROM SICEX.TAM052 WHERE SACRG=1) " )
    .append("AND O.ESTOPEVTA IN ('P','F') ORDER BY A.NUMOPE,B.NROOI,I.NRODOCID,J.CODMON ").toString();
	
	public static final String COTIZACION2 = new StringBuilder(" SELECT A.NUMOPE,B.NROOI , B.SIGLA || B.SERIE AS CONTENEDOR,F.CODSRVCO,I.NRODOCID,A.FECOPE,E.CODMON, " )
    .append("D.IMPCST AS IMP_SILE,F.CDRFCODMAT,F.NCCSAP,A.FECOPE,C.NROPEDI,C.FLGPEDI,C.IMPPEDI AS IMP_PEDIDO," )
    .append("CASE WHEN D.IDSRVCO IS NOT NULL THEN 'ADICIONAL' END AS TIPO, F.DESSRVCO, I.RZINLO ,C.IDOPEPED " )
    .append("FROM SICEX.TBN011 A " )
    .append("INNER JOIN SICEX.TBN014 B ON A.IDOPE=B.IDOPE AND B.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN016 C ON C.IDOPETCOI=B.IDOPETCOI  AND C.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN013 D ON D.IDOPECST=C.IDOPECST AND D.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM013 E ON E.IDMON=D.IDMON AND E.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM020 F ON F.IDSRVCO=D.IDSRVCO AND F.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM031 H ON H.IDINLOUNRL=D.IDPROV  AND H.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM018 I ON I.IDINLOCTR=H.IDINLOCTR AND I.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN012 J ON J.IDOPEVTA=D.IDOPEVTA AND J.IDOPE=A.IDOPE AND J.IDSRVTAUN IS NOT NULL AND J.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN015 K ON K.IDOPETCOI=B.IDOPETCOI AND K.IDOPEVTA=J.IDOPEVTA AND K.SACRG=1 " )
    .append("WHERE D.ESTOPECST='A' AND A.SACRG=1 AND C.NROPEDI=0 AND " )
    .append("I.NRODOCID NOT IN (SELECT RUCPRO FROM SICEX.TAM052 WHERE SACRG=1) " )
    .append("AND J.ESTOPEVTA IN ('P' ,'F') ORDER BY A.NUMOPE,B.NROOI,I.NRODOCID,J.CODMON ").toString();
	
	public static final String COTIZACION3 = new StringBuilder("SELECT A.NUMOPE,B.NROOI , B.SIGLA || B.SERIE AS CONTENEDOR,K.CODSRVCO,I.NRODOCID,A.FECOPE,J.CODMON, " )
    .append("E.IMPSCPR AS IMP_SILE,K.CDRFCODMAT,K.NCCSAP,A.FECOPE,C.NROPEDI,C.FLGPEDI,C.IMPPEDI AS IMP_PEDIDO, " )
    .append("CASE WHEN D.IDCONDET IS NOT NULL THEN 'CAMBIO_PROV' END AS TIPO, K.DESSRVCO , I.RZINLO ,C.IDOPEPED " )
    .append("FROM SICEX.TBN011 A " )
    .append("INNER JOIN SICEX.TBN014 B ON A.IDOPE=B.IDOPE AND B.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN016 C ON C.IDOPETCOI=B.IDOPETCOI  AND C.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN013 D ON D.IDOPECST=C.IDOPECST AND D.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN002 E ON E.IDCONDET=D.IDCONDET AND E.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN001 F ON  F.IDCONPRV=E.IDCONPRV AND F.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM031 G ON G.IDINLOUNRL=F.IDINLOUNRL AND G.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM005 H ON H.IDTPROL=G.IDTPROL AND H.CODTPROL=2 AND H.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM018 I ON I.IDINLOCTR=G.IDINLOCTR AND I.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM013 J ON J.IDMON=E.IDMON AND J.SACRG=1 " )
    .append("INNER JOIN SICEX.TAM020 K ON K.IDSRVCO=E.IDSRVCO AND K.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN012 M ON M.IDOPEVTA=D.IDOPEVTA AND M.IDOPE=A.IDOPE AND M.SACRG=1 " )
    .append("INNER JOIN SICEX.TBN015 N ON N.IDOPETCOI=B.IDOPETCOI AND N.IDOPEVTA=M.IDOPEVTA AND N.SACRG=1 " )
    .append("WHERE D.ESTOPECST='A' AND A.SACRG=1 AND C.NROPEDI=0 AND " )
    .append("I.NRODOCID NOT IN (SELECT RUCPRO FROM SICEX.TAM052 WHERE SACRG=1) " )
    .append("AND M.ESTOPEVTA IN ('P' ,'F') ORDER BY A.NUMOPE,B.NROOI,I.NRODOCID,J.CODMON ").toString();
	
	
	
	
	
	
	
	
	
	
	
//	SELECT  A.NUMOPE,B.NROOI, B.SIGLA || B.SERIE AS CONTENEDOR,J.CODSRVCO,I.NRODOCID,A.FECOPE,K.CODMON,   
//	F.IMPSCPR AS IMP_SILE,J.CDRFCODMAT,J.NCCSAP,A.FECOPE,C.NROPEDI,C.FLGPEDI,C.IMPPEDI AS IMP_PEDIDO,  
//	CASE WHEN D.IDCSTCNTCL IS NOT NULL THEN 'COTIZADO' END AS TIPO, J.DESSRVCO, I.RZINLO,C.IDOPEPED   
//	FROM SICEX.TBN011 A   
//	INNER JOIN SICEX.TBN014 B ON A.IDOPE=B.IDOPE AND B.SACRG=1   
//	INNER JOIN SICEX.TBN016 C ON C.IDOPETCOI=B.IDOPETCOI  AND C.SACRG=1   
//	INNER JOIN SICEX.TBN013 D ON D.IDOPECST=C.IDOPECST AND D.SACRG=1   
//	INNER JOIN SICEX.TBN006 E ON E.IDCSTCNTCL=D.IDCSTCNTCL AND E.SACRG=1   
//	INNER JOIN SICEX.TBN002 F ON F.IDCONDET=E.IDCONDET AND F.SACRG=1   
//	INNER JOIN SICEX.TBN001 G ON G.IDCONPRV=F.IDCONPRV AND G.SACRG=1   
//	INNER JOIN SICEX.TAM031 H ON H.IDINLOUNRL=G.IDINLOUNRL AND H.SACRG=1   
//	INNER JOIN SICEX.TAM018 I ON I.IDINLOCTR=H.IDINLOCTR AND I.SACRG=1   
//	INNER JOIN SICEX.TAM020 J ON J.IDSRVCO=F.IDSRVCO AND J.SACRG=1   
//	INNER JOIN SICEX.TAM013 K ON K.IDMON=F.IDMON AND K.SACRG=1   
//	INNER JOIN SICEX.TBN004 M ON M.IDCNTCLCAB=A.IDCNTCLCAB AND M.SACRG=1   
//	INNER JOIN SICEX.TBN005 N ON N.IDCNTCLCAB=M.IDCNTCLCAB AND N.SACRG=1   
//	INNER JOIN SICEX.TBN012 O ON O.IDOPEVTA=D.IDOPEVTA  AND O.IDOPE=A.IDOPE AND O.IDCNTCLDET=N.IDCNTCLDET AND O.SACRG=1   
//	INNER JOIN SICEX.TBN015 P ON P.IDOPETCOI=B.IDOPETCOI AND P.IDOPEVTA=O.IDOPEVTA AND P.SACRG=1   
//	WHERE A.SACRG=1 AND D.ESTOPECST='A' AND C.NROPEDI=0 AND   
//	I.NRODOCID NOT IN (SELECT RUCPRO FROM SICEX.TAM052 WHERE SACRG=1)   
//	AND O.ESTOPEVTA IN ('P','F') ORDER BY A.NUMOPE,B.NROOI,I.NRODOCID,J.CODMON  
	
//	SELECT A.NUMOPE,B.NROOI , B.SIGLA || B.SERIE AS CONTENEDOR,F.CODSRVCO,I.NRODOCID,A.FECOPE,E.CODMON,    
//	D.IMPCST AS IMP_SILE,F.CDRFCODMAT,F.NCCSAP,A.FECOPE,C.NROPEDI,C.FLGPEDI,C.IMPPEDI AS IMP_PEDIDO,   
//	CASE WHEN D.IDSRVCO IS NOT NULL THEN 'ADICIONAL' END AS TIPO, F.DESSRVCO, I.RZINLO ,C.IDOPEPED    
//	FROM SICEX.TBN011 A    
//	INNER JOIN SICEX.TBN014 B ON A.IDOPE=B.IDOPE AND B.SACRG=1    
//	INNER JOIN SICEX.TBN016 C ON C.IDOPETCOI=B.IDOPETCOI  AND C.SACRG=1    
//	INNER JOIN SICEX.TBN013 D ON D.IDOPECST=C.IDOPECST AND D.SACRG=1    
//	INNER JOIN SICEX.TAM013 E ON E.IDMON=D.IDMON AND E.SACRG=1    
//	INNER JOIN SICEX.TAM020 F ON F.IDSRVCO=D.IDSRVCO AND F.SACRG=1    
//	INNER JOIN SICEX.TAM031 H ON H.IDINLOUNRL=D.IDPROV  AND H.SACRG=1    
//	INNER JOIN SICEX.TAM018 I ON I.IDINLOCTR=H.IDINLOCTR AND I.SACRG=1    
//	INNER JOIN SICEX.TBN012 J ON J.IDOPEVTA=D.IDOPEVTA AND J.IDOPE=A.IDOPE AND J.IDSRVTAUN IS NOT NULL AND J.SACRG=1    
//	INNER JOIN SICEX.TBN015 K ON K.IDOPETCOI=B.IDOPETCOI AND K.IDOPEVTA=J.IDOPEVTA AND K.SACRG=1    
//	WHERE D.ESTOPECST='A' AND A.SACRG=1 AND C.NROPEDI=0 AND    
//	I.NRODOCID NOT IN (SELECT RUCPRO FROM SICEX.TAM052 WHERE SACRG=1)    
//	AND J.ESTOPEVTA IN ('P' ,'F') ORDER BY A.NUMOPE,B.NROOI,I.NRODOCID,J.CODMON  
	
//	SELECT A.NUMOPE,B.NROOI , B.SIGLA || B.SERIE AS CONTENEDOR,K.CODSRVCO,I.NRODOCID,A.FECOPE,J.CODMON,    
//	E.IMPSCPR AS IMP_SILE,K.CDRFCODMAT,K.NCCSAP,A.FECOPE,C.NROPEDI,C.FLGPEDI,C.IMPPEDI AS IMP_PEDIDO,    
//	CASE WHEN D.IDCONDET IS NOT NULL THEN 'CAMBIO_PROV' END AS TIPO, K.DESSRVCO , I.RZINLO ,C.IDOPEPED    
//	FROM SICEX.TBN011 A    
//	INNER JOIN SICEX.TBN014 B ON A.IDOPE=B.IDOPE AND B.SACRG=1    
//	INNER JOIN SICEX.TBN016 C ON C.IDOPETCOI=B.IDOPETCOI  AND C.SACRG=1    
//	INNER JOIN SICEX.TBN013 D ON D.IDOPECST=C.IDOPECST AND D.SACRG=1    
//	INNER JOIN SICEX.TBN002 E ON E.IDCONDET=D.IDCONDET AND E.SACRG=1    
//	INNER JOIN SICEX.TBN001 F ON  F.IDCONPRV=E.IDCONPRV AND F.SACRG=1    
//	INNER JOIN SICEX.TAM031 G ON G.IDINLOUNRL=F.IDINLOUNRL AND G.SACRG=1    
//	INNER JOIN SICEX.TAM005 H ON H.IDTPROL=G.IDTPROL AND H.CODTPROL=2 AND H.SACRG=1    
//	INNER JOIN SICEX.TAM018 I ON I.IDINLOCTR=G.IDINLOCTR AND I.SACRG=1    
//	INNER JOIN SICEX.TAM013 J ON J.IDMON=E.IDMON AND J.SACRG=1    
//	INNER JOIN SICEX.TAM020 K ON K.IDSRVCO=E.IDSRVCO AND K.SACRG=1    
//	INNER JOIN SICEX.TBN012 M ON M.IDOPEVTA=D.IDOPEVTA AND M.IDOPE=A.IDOPE AND M.SACRG=1    
//	INNER JOIN SICEX.TBN015 N ON N.IDOPETCOI=B.IDOPETCOI AND N.IDOPEVTA=M.IDOPEVTA AND N.SACRG=1    
//	WHERE D.ESTOPECST='A' AND A.SACRG=1 AND C.NROPEDI=0 AND    
//	I.NRODOCID NOT IN (SELECT RUCPRO FROM SICEX.TAM052 WHERE SACRG=1)    
//	AND M.ESTOPEVTA IN ('P' ,'F') ORDER BY A.NUMOPE,B.NROOI,I.NRODOCID,J.CODMON  
	
	
	
	
	
	
	
	
	
	
	
	
	
}
